name: Publish to PyPI

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - "release"
      - "release/**"
      - "beta"
      - "beta/**"

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-upload:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'release')
    env:
      GH_TOKEN: ${{ github.token }}
      index-repo: aioqzone/aioqzone-index
    permissions:
      contents: write # release needs write permission
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          # cache: poetry

      #----------------------------------------------
      #  --------    Build and release   ---------
      #----------------------------------------------
      - name: Build dist and Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
